### ISSUE TITLE
Unnessesary files published

### ISSUE THREAD

**Issue by jaydenseric** [mike-marcacci/fs-capacitor#12]
I haven't worked out why yet, but for some reason unnecessary files such as dev tool config files and `yarn.lock` have been mistakenly published to npm:

https://unpkg.com/fs-capacitor@2.0.4/

**Comment by mike-marcacci** [comment]
Very interesting! I wonder if yarn’s version of `publish` is not respecting the config. I’ll explore this a little later today and try publishing a patch.

**Comment by mike-marcacci** [comment]
This appears fixed in `v4-beta2`
