### ISSUE TITLE
Cannot extend an interface 'FSWriteStream'. Did you mean 'implements'?

### ISSUE THREAD

**Issue by j-gibweb** [mike-marcacci/fs-capacitor#13]
![image](https://user-images.githubusercontent.com/3903952/67443212-c33f3d80-f5b8-11e9-810c-4ab416957c3e.png)

I'm not sure I understand why the classes are namespaced under `tty` instead of `fs` like you have in the module, its probably local to my machine? or not? idk, but `ReadStream` / `WriteStream` from `fs` are interfaces, hence the error

```
- import { ReadStream as FSReadStream, WriteStream as FSWriteStream } from "fs";
+ import { ReadStream as FSReadStream, WriteStream as FSWriteStream } from "tty";
```

Any insight would be great, thanks

This is from version 2.0.0

**Comment by mike-marcacci** [comment]
Hi @j-gibweb, this is quite odd... Are the type definitions coming from DefinitelyTyped? They [definitely import the stream classes from `fs`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/fs-capacitor/index.d.ts).

**Comment by j-gibweb** [comment]
@mike-marcacci the definitions are indeed coming from DefinitelyTyped 

poking around a bit more I see the version of `fs` being referenced is from "@types/node@7.10.7"- is this expected?

**Comment by mike-marcacci** [comment]
Hmm, definitely not... the library definition specifies [`/// <reference types="node" />`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/12a9dee9a5e7c7821816d1da782653ddc4b25b46/types/fs-capacitor/index.d.ts#L7) so I'm curious if you have something else specifying that version of node in your typescript config?

**Comment by j-gibweb** [comment]
This has mysteriously been resolved 😞 - Thanks for being so responsive
