### ISSUE TITLE
Node.js 13: ReadStream.prototype.open() is deprecated

### ISSUE THREAD

**Issue by janokacer** [mike-marcacci/fs-capacitor#15]
ReadStream.prototype.open() has been deprecated in [Node.js 13.0.1](deprecations_dep0135_writestream_open_and_readstream_open_are_internal). I think this is the reason why WriteStream.prototype.createReadStream() causes: "RangeError: Maximum call stack size exceeded".

Code to reproduce:
```js
const {WriteStream} = require('fs-capacitor')
const fs = require('fs')

const stream = fs.createReadStream('package-lock.json')
const capacitor = new WriteStream()

stream.pipe(capacitor)
capacitor.createReadStream()
```

**Comment by mike-marcacci** [comment]
Thanks for the report @janokacer. I'm planning to take the approach suggested by @ronag in #14, and will probably cut a major version sometime this week to more closely match the API changes in node 13.

**Comment by mike-marcacci** [comment]
This should be fixed in version 3, and also in the version 4 beta.
