### ISSUE TITLE
It would be useful if file size could be checked

### ISSUE THREAD

**Issue by fabis94** [mike-marcacci/fs-capacitor#27]
Once the file is stored in the temp directory, its file size could be checked with `fs.fstat()` right? It would probably be faster than reading the entire `ReadStream` to get the total byte count and would be useful for validating upload size.

Maybe the `ReadStream` interface of this package could be adjusted to also include a method for checking the file size, which would execute `fs.fstat()` behind the scenes.

**Comment by jaydenseric** [comment]
> Once the file is stored in the temp directory, its file size could be checked with `fs.fstat()` right?

Note that the file is not completely uploaded to the temp directory before readstreams access it; rather the file gets read via potentially multiple read streams as it is streaming in.

**Comment by mike-marcacci** [comment]
Hey @fabis94 you may want to reassess why filesize is important to you. The general point of streams is to process data as it becomes available, and it would be highly suboptimal to wait for a stream to finish before beginning to process it.

The intent of the `fs-capacitor` library is to support this paradigm in scenarios like `graphql-upload` where it's impossible to guarantee that all forks of a stream are created in the same processor tick. Therefore, while it _does_ buffer to the filesystem, it's designed to be read from _as it's being written to_.

What you _probably_ want is to commence your upload as soon as possible, and then error (destroying any newly-created resources) if/when your max file size is exceeded.

```ts
const { Transform } = require('stream')

const maxFileSize = 100000000;
class Counter extends Transform {
  _transform (chunk, encoding, callback) {
    this.length += chunk.length

    if (this.length > maxFileSize) {
    	this.destroy(new Error(`Max file size of ${maxFileSize} exceeded.`));
    }

    this.push(chunk)
    callback()
  }
}

// Create a new counter and propagate the error in both directions.
const counter = new Counter();
counter.on("error", error => {
	source.destroy(error);
	destination.destroy(error);
});

// Connect your streams.
source
	.pipe(counter)
	.pipe(destination)
```

**Comment by fabis94** [comment]
Thanks, ended up doing something like that
