### ISSUE TITLE
Builds fail due to TypeScript errors

### ISSUE THREAD

**Issue by jaydenseric** [mike-marcacci/fs-capacitor#29]
With freshly installed `node_modules`, running `npm run prepare` results in TypeScript errors:

https://travis-ci.org/github/mike-marcacci/fs-capacitor/jobs/690761205#L212-L225

**Comment by mike-marcacci** [comment]
This is updated on master, but it will continue to fail until this is fixed:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45087#pullrequestreview-418861568

Once that gets merged and published, I'll cut a new release.

**Comment by mike-marcacci** [comment]
My typescript PR was a duplicate. Tracking this one for a fix instead: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44999

**Comment by mike-marcacci** [comment]
Fixed and published as v6.2.0.
