### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by gabegorelick** [mike-marcacci/fs-capacitor#30]
`fs-capacitor` registers a `exit` and a `SIGINT` listener for each `WriteStream` created. This means that when constructing a lot of WriteStreams at once, you'll often run into Node's `MaxListenersExceededWarning`:

> (node:63179) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit

> (node:63179) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit

An alternative would be to register a single handler and use a global list of objects to clean up. This technique is used by prominent modules like [`tmp`](https://github.com/raszi/node-tmp/blob/7ae22ed2d56c10d425a66e99fe8bc10c925442e6/lib/tmp.js#L670).

**Comment by gabegorelick** [comment]
https://github.com/mike-marcacci/fs-capacitor/issues/1 mentions that this was fixed in v1.0.0. That may be true, but it doesn't appear to be fixed on master.

**Comment by mike-marcacci** [comment]
Hi @gabegorelick - thanks for creating this. Regarding #1, that fix is in reference to a different issue related to listening, which would trigger the same warning.

Just to confirm, your proposed solution is simply intended to hack around node's warning, correct? That is, you aren't reporting a leak, just the fact that your application creates these streams with sufficient concurrency to trigger this warning, right?

I'm not totally opposed to working around this here, but it also feels like the end result is functionally equivalent, just without a warning. Do you see this as preferable to following the warning's guidance of calling `process.setMaxListeners(100);` or similar in your project?

**Comment by gabegorelick** [comment]
> That is, you aren't reporting a leak, just the fact that your application creates these streams with sufficient concurrency to trigger this warning, right?

You're correct that I haven't encountered a leak, although registering multiple listeners, as opposed to one, increases the risk of a leak in theory.

> I'm not totally opposed to working around this here, but it also feels like the end result is functionally equivalent to the current behavior, just without the possibility of triggering node's warning. Do you see this as preferable to following the warning's guidance of calling process.setMaxListeners(100); or similar in your project?

Correct, the end result should be more or less functionally equivalent. But the advantage is that users don't have to call `setMaxListeners`. `setMaxListeners` is a blunt instrument: there's no way to say "I'm fine with `fs-capacitor` registering 1000 exit listeners". Instead, you have to allow everyone to register 1000 listeners on `process`. So `setMaxListeners` is almost never a good solution in my experience.

**Comment by mike-marcacci** [comment]
Hi @gabegorelick, I know you've been waiting on this for a while. I just opened #42 as a more concise alternative to #34. Could you give that a look over and see if it addresses your use-case here?
