### ISSUE TITLE
Support for commonjs missing, Typescript types not packaged by npm

### ISSUE THREAD

**Issue by mernxl** [mike-marcacci/fs-capacitor#53]
Hello, I had these issues when updating to the latest version of this library.

- Types have not been packaged by npm from the internal typescript index.ts file, i had to revert to using **@types/fs-capacitor**. Having one less dependency would be nice.
- Please can you add support for commonjs? Transpiling code to JS using WebPack in **commonjs**, breaks most of my repositories. Including a .cjs version of your code will really help out a lot. 

I believe most node code bases are written in commonjs or use a bundler from Typescript so solving this issue will greatly reduce some headaches. 

I can submit a pull request in case my worries are worth looking into. Just wanted to understand your reasons for dropping support for **commonjs** before making a pull request.

Thanks

**Comment by mike-marcacci** [comment]
Hi @mernxl, great catch with the missing definition file. This should be fixed by #54.

Regarding publishing of ES modules vs commonjs, the hope for version 7 was to fully transition this (as a "leaf" repository with no production dependencies of its own) to modules, in hopes that it would simplify this transition now that node 10 has reached EOL and all target runtimes support this out of the box.

Can you describe your use-case and setup with webpack a bit more? Given the nature of this project and its heavy reliance on node APIs I was not really expecting it to be used in workflows involving bundlers.

**Comment by mernxl** [comment]
Actually i use WebPack to bundle my typescript API code (actually multiple .ts into a single file) before i deploy to the server. 

I try to take advantage of tree-shaking and the minified bundles for production. 

Actually as i was exploring different options to load up the es module files, i ended up using [webpack-node-externals](https://github.com/liady/webpack-node-externals) to manage externals and added fs-capacitor as an allowed package, so its bundled into my final code.

```js
const path = require('path');
const nodeExternals = require('webpack-node-externals');

module.exports = (env) => {
  const RELEASE = env.production;

  return {
    target: 'node',
    externalsPresets: { node: true },
    mode: RELEASE ? 'production' : 'development',
    entry: './src/index.ts',
    devtool: 'inline-source-map',
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          use: 'ts-loader',
          exclude: /node_modules/,
        },
      ],
    },
    resolve: {
      extensions: ['.js', '.ts'],
    },
    externals: [nodeExternals({ allowlist: ['fs-capacitor'] })], // added fs-capacitor so its bundled
    output: {
      filename: 'index.js',
      path: path.join(__dirname, 'build'),
    },
  };
};
```

Before, i had a small function that returned a list of modules (in node_modules) that were not to be bundled into my code.

So i can say i found a workaround for the issue. I explored multiple options and that is the only on that seems to work.

**Comment by mike-marcacci** [comment]
Ah OK this is good to know. I'm glad you found a workaround; I'm going to go ahead and merge/release that fix for the types, but I'll hold off on adding back commonjs unless this pattern proves to be prevalent.

**Comment by mernxl** [comment]
Ok, thanks. I guess is someone is using this pattern he may come across this issue. Thanks you.

**Comment by mike-marcacci** [comment]
Yes, indeed - thanks for publishing your workaround :) Version `7.0.1` should be out now - do let me know if you have any issues with it!
