### ISSUE TITLE
No write event emiter

### ISSUE THREAD

**Issue by Nikosmonaut** [mike-marcacci/fs-capacitor#9]
When unread === 0 we add listeners on write and finish events.
But it seems the write event is never emited.

So the problem I have is when my writeStream has no more to read because the upload is too slow it waits to the finish event (full upload) before restart writing.

![image](https://user-images.githubusercontent.com/45662151/57013973-438a7480-6c0e-11e9-92ef-49c79d9b350a.png)

Do you think it should be added manually. Because I can not find a write event in nodejs doc.

![image](https://user-images.githubusercontent.com/45662151/57014114-e3480280-6c0e-11e9-80cd-78134c0b43f1.png)

**Comment by mike-marcacci** [comment]
Thanks so much for the detailed investigation! I am slammed today but I’ll look into this tomorrow. Keep posting if you learn anything more!

**Comment by Nikosmonaut** [comment]
No hurry :).
I don't think I can dig more than this solution. It seems we should manually call emit on write event when a _write occurs.

I ran your tests and all passes. In my case it fix the problem but I can not foresee all cases when it could misbehave.

**Comment by mike-marcacci** [comment]
Thanks so much for the investigation @Nikosmonaut! It looks like I inadvertently removed the event [in this commit](https://github.com/mike-marcacci/fs-capacitor/commit/8b3ad8839eeb9ba8d01deced08bf74c7611a6e38#diff-4a667ee0049f3ff3aa6da6ac7653fad3L172) and didn't have tests to protect against this kind of timing bug.

The correct behavior has been restored (along with some new tests) and is published as a patch.
